global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: bff-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8088']

  - job_name: search-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: autocomplete-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: ranking-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: commerce-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8091']

  - job_name: outbox-relay-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8095']

  - job_name: olap-loader-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8096']
