server:
  port: ${AUTOCOMPLETE_PORT:8081}

spring:
  application:
    name: autocomplete-service

app:
  cors:
    allowed-origins: "http://localhost:4173,http://localhost:5173,http://localhost:5174"
    allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
    allowed-headers: "*"
    exposed-headers: "x-trace-id,x-request-id"
    allow-credentials: true

opensearch:
  url: ${OPENSEARCH_URL:http://localhost:9200}
  username: ${OPENSEARCH_USERNAME:}
  password: ${OPENSEARCH_PASSWORD:}
  timeout-ms: 300
  index: ac_suggest_read

logging:
  level:
    root:
      DEBUG
